# Generated by Django 3.2.2 on 2021-05-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_category', '0002_tag'),
        ('article', '0007_auto_20210519_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article_category.Tag'),
        ),
    ]
