# Generated by Django 3.2.2 on 2021-05-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('article', '0008_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='media.photo'),
        ),
    ]
